name: Build

on:
  push:
    branches:
      - '**'

jobs:
  dotnet-test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
      - shell: bash
        run: |
          dotnet test

  docker-build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4
      - name: Build service
        uses: docker/build-push-action@v7
        with:
          push: false
          context: .
          target: service
          tags: cathal-dotnet-docker-multistage/service:latest
          platforms: linux/amd64,linux/arm64
      - name: Build web
        uses: docker/build-push-action@v7
        with:
          push: false
          context: .
          target: web
          tags: cathal-dotnet-docker-multistage/web:latest
          platforms: linux/amd64,linux/arm64

  podman-build:
    runs-on: 'ubuntu-26.04' # Podman version downgraded on ubuntu-latest. See https://github.com/actions/runner-images/issues/14642
    steps:
      - uses: actions/checkout@v7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Build service
        shell: bash
        run: |
          podman manifest rm cathal-dotnet-podman-multistage/service:latest 2>/dev/null || true
          podman manifest create cathal-dotnet-podman-multistage/service:latest
          podman build \
            --platform linux/amd64,linux/arm64 \
            --manifest cathal-dotnet-podman-multistage/service:latest \
            --target service \
            .
      - name: Build web
        shell: bash
        run: |
          podman manifest rm cathal-dotnet-podman-multistage/web:latest 2>/dev/null || true
          podman manifest create cathal-dotnet-podman-multistage/web:latest
          podman build \
            --platform linux/amd64,linux/arm64 \
            --manifest cathal-dotnet-podman-multistage/web:latest \
            --target web \
            .
